name: Z Re-usable create release branch

on:
  workflow_dispatch:
    inputs:
      RELEASE_BRANCH_NAME:
        description: 'Release branch date YYYY-MM-DD'
        required: true
        type: string
      SOURCE_REPO:
        required: true
        type: string

jobs:
  create-release-branch:

    name: Create release branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: QuickFee/${{ inputs.SOURCE_REPO }}
          ref: main
#          token: ${{ secrets.PAT }}

      - name: Checkout release branch
        run: |
          git checkout -b ${{ inputs.RELEASE_BRANCH_NAME }} HEAD --

      - name: Push Release branch
        run: |
          git -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/${{ inputs.RELEASE_BRANCH_NAME }}:refs/heads/${{ inputs.RELEASE_BRANCH_NAME }} --set-upstream
